# Generated by Django 3.2.4 on 2021-06-12 21:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=100)),
                ('start_time', models.CharField(default='2021061221151623532554', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('bike', models.ForeignKey(on_delete=api.models.Bike, to='api.bike')),
                ('user', models.ForeignKey(on_delete=api.models.User, to='api.user')),
            ],
        ),
    ]
